import type { Element } from "@contracts/fengshui";

/** Gaode POI type codes per element — kept in sync with `src/data/elements.ts` */
export const GAODE_TYPES: Record<Element, string> = {
  木: "110100|110000|210000",
  水: "210000|110100",
  火: "110105|080000|050500",
  土: "140300|140600|140200",
  金: "050500|060600|140200",
};

export const WIKI_LANG_MAP: Record<string, string> = {
  CN: "zh",
  TW: "zh",
  HK: "zh",
  MO: "zh",
  US: "en",
  GB: "en",
  AU: "en",
  CA: "en",
  NZ: "en",
  IE: "en",
  JP: "ja",
  KR: "ko",
  SG: "en",
  FR: "fr",
  DE: "de",
  ES: "es",
  IT: "it",
  RU: "ru",
  BR: "pt",
  IN: "en",
  MX: "es",
  AR: "es",
  CL: "es",
  CO: "es",
  PE: "es",
  ZA: "en",
  NL: "nl",
  BE: "nl",
  CH: "de",
  AT: "de",
  SE: "sv",
  NO: "no",
  DK: "da",
  FI: "fi",
  PL: "pl",
  CZ: "cs",
  HU: "hu",
  TR: "tr",
  GR: "el",
  PT: "pt",
  TH: "th",
  VN: "vi",
  ID: "id",
  MY: "en",
  PH: "en",
  AE: "en",
  SA: "ar",
  EG: "ar",
  IL: "he",
  UA: "uk",
  RO: "ro",
  BG: "bg",
  HR: "hr",
  RS: "sr",
  SI: "sl",
  SK: "sk",
  LT: "lt",
  LV: "lv",
  EE: "et",
};
